import { ArchitectureReview, ArchitectureReviewCategory, ArchitectureReviewEvidence, ArchitectureReviewFinding, ArchitectureReviewHistory, ArchitectureReviewRecommendation, ArchitectureReviewStats, ArchitectureReviewSummary, ArchitectureStrength } from "@/types/ai-architecture-review-ui";

const MOCK_STATS: ArchitectureReviewStats = {
  score: 86,
  confidence: 93,
  totalFindings: 14,
  critical: 1,
  high: 3,
  medium: 6,
  low: 4,
  recommendations: 9,
};

const MOCK_CATEGORIES: ArchitectureReviewCategory[] = [
  { category: "ARCHITECTURE", score: 91, explanation: "Strong adherence to clean architecture principles." },
  { category: "BOUNDARIES", score: 82, explanation: "Several cross-layer dependencies reduce architectural isolation." },
  { category: "DEPENDENCIES", score: 79, explanation: "Circular dependencies and high coupling identified." },
  { category: "SECURITY", score: 94, explanation: "Well-isolated authentication and minimal data leakage." },
  { category: "MAINTAINABILITY", score: 86, explanation: "Most modules have low cyclomatic complexity." },
  { category: "SCALABILITY", score: 88, explanation: "Good service modularity allows horizontal scaling." },
  { category: "PERFORMANCE", score: 90, explanation: "Efficient data access patterns detected." },
];

const MOCK_SUMMARY: ArchitectureReviewSummary = {
  assessment: "CodeAtlas currently demonstrates a strong layered architecture with clear separation between presentation, application, domain, and infrastructure concerns. The primary architectural risks are concentrated around dependency direction, authentication boundaries, and infrastructure leakage.",
  strengths: [
    "Clear layered architecture",
    "Strong domain separation",
    "Controlled external dependencies",
    "Good service modularity",
  ],
  concerns: [
    "Several cross-layer dependencies",
    "Authentication boundary coupling",
    "Circular dependency cluster",
    "Infrastructure leakage",
  ],
};

const MOCK_STRENGTHS: ArchitectureStrength[] = [
  { id: "str-1", title: "Strong Layer Separation", score: 92, explanation: "Domain models are completely independent of infrastructure concerns.", components: ["DomainCore", "ProjectEntities"] },
  { id: "str-2", title: "Domain Isolation", score: 89, explanation: "Bounded contexts maintain high cohesion and low coupling.", components: ["AnalysisService", "UserDomain"] },
  { id: "str-3", title: "Service Modularity", score: 87, explanation: "Services expose well-defined interfaces.", components: ["AuthService", "ProjectService"] },
  { id: "str-4", title: "External Dependency Control", score: 91, explanation: "Third-party libraries are isolated behind interfaces.", components: ["PaymentAdapter", "EmailSender"] },
  { id: "str-5", title: "Testability", score: 84, explanation: "Dependency injection enables straightforward unit testing.", components: ["DependencyAnalyzer", "RepositoryService"] },
];

const MOCK_FINDINGS: ArchitectureReviewFinding[] = [
  {
    id: "fnd-1",
    title: "Cross-Layer Dependency Detected",
    severity: "HIGH",
    category: "BOUNDARIES",
    status: "OPEN",
    confidence: 96,
    affectedComponents: ["ProjectService", "PostgresRepository"],
    description: "Application service directly imports infrastructure implementation.",
    whyItMatters: "Direct infrastructure dependencies inside the application layer reduce portability and make domain-level testing more difficult.",
    evidence: "ProjectService → PostgresRepository",
    architectureImpact: "Application → Infrastructure",
    risk: "High coupling preventing database migration and unit testing.",
    suggestedRemediation: ["Introduce repository interface", "Move implementation behind infrastructure boundary", "Inject abstraction into application service"],
  },
  {
    id: "fnd-2",
    title: "Circular Dependency Cluster",
    severity: "CRITICAL",
    category: "DEPENDENCIES",
    status: "OPEN",
    confidence: 98,
    affectedComponents: ["AnalysisService", "ArchitectureService", "DependencyAnalyzer"],
    description: "Three core services have cyclical references preventing independent deployment.",
    whyItMatters: "Cycles cause tight coupling, slow build times, and runtime initialization issues.",
    evidence: "Cycle: AnalysisService → ArchitectureService → DependencyAnalyzer → AnalysisService",
    architectureImpact: "Application Layer Cycles",
    risk: "Cascading failures during service updates.",
    suggestedRemediation: ["Extract shared interface", "Use event-driven communication", "Merge tightly cohesive services"],
  },
  {
    id: "fnd-3",
    title: "Authentication Boundary Coupling",
    severity: "HIGH",
    category: "ARCHITECTURE",
    status: "OPEN",
    confidence: 91,
    affectedComponents: ["UserService", "AuthService", "RedisRepository"],
    description: "Authentication logic is scattered across unrelated services.",
    whyItMatters: "Increases security risk and makes changing auth providers costly.",
    evidence: "6 cross-layer dependencies detected across 3 services.",
    architectureImpact: "Cross-Domain Coupling",
    risk: "Security policy bypass possible.",
    suggestedRemediation: ["Centralize Auth Middleware", "Remove direct Redis access from UserService"],
  },
  {
    id: "fnd-4",
    title: "Infrastructure Dependency Exposure",
    severity: "HIGH",
    category: "BOUNDARIES",
    status: "ACKNOWLEDGED",
    confidence: 85,
    affectedComponents: ["APIControllers"],
    description: "Infrastructure objects exposed to HTTP response.",
    whyItMatters: "Data leakage risk.",
    evidence: "UserEntity exposed directly.",
    architectureImpact: "Presentation Layer",
    risk: "Information disclosure.",
    suggestedRemediation: ["Use DTOs"],
  },
  // 6 Mediums
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `fnd-med-${i}`,
    title: `Domain Isolation Weakness ${i + 1}`,
    severity: "MEDIUM" as const,
    category: "MAINTAINABILITY" as const,
    status: "OPEN" as const,
    confidence: 88 - i,
    affectedComponents: [`Component${i}A`, `Component${i}B`],
    description: "Minor domain leakage.",
    whyItMatters: "Slightly reduces code readability.",
    evidence: "Shared constants.",
    architectureImpact: "Domain",
    risk: "Low.",
    suggestedRemediation: ["Separate constants"],
  })),
  // 4 Lows
  ...Array.from({ length: 4 }).map((_, i) => ({
    id: `fnd-low-${i}`,
    title: `High-Complexity Service ${i + 1}`,
    severity: "LOW" as const,
    category: "PERFORMANCE" as const,
    status: "RESOLVED" as const,
    confidence: 75,
    affectedComponents: [`Service${i}`],
    description: "Method is quite long.",
    whyItMatters: "Harder to maintain.",
    evidence: "Cyclomatic complexity > 15.",
    architectureImpact: "Application",
    risk: "Bugs.",
    suggestedRemediation: ["Refactor into smaller functions"],
  })),
];

const MOCK_RECOMMENDATIONS: ArchitectureReviewRecommendation[] = [
  {
    id: "rec-1",
    title: "Introduce Repository Abstraction",
    priority: "HIGH",
    confidence: 94,
    problem: "Direct infrastructure coupling in ProjectService.",
    evidence: "ProjectService -> PostgresRepository",
    affectedComponents: ["ProjectService", "PostgresRepository"],
    expectedArchitecture: "Application ↓ Repository Interface ↓ Infrastructure Implementation",
    currentArchitecture: "Application ↓ PostgresRepository",
    expectedBenefit: "High portability and testability",
    estimatedEffort: "MEDIUM",
    suggestedSteps: ["Create IProjectRepository in Domain", "Implement in Infrastructure", "Inject in App"],
    status: "OPEN",
  },
  {
    id: "rec-2",
    title: "Isolate Authentication Boundary",
    priority: "HIGH",
    confidence: 96,
    problem: "Auth logic scattered.",
    evidence: "Multiple services check tokens.",
    affectedComponents: ["AuthService", "API"],
    expectedArchitecture: "API Gateway handles Auth -> Services are blind",
    currentArchitecture: "Services perform Auth checks inline",
    expectedBenefit: "Centralized security",
    estimatedEffort: "HIGH",
    suggestedSteps: ["Move auth to middleware", "Pass user context"],
    status: "OPEN",
  },
  {
    id: "rec-3",
    title: "Break Circular Dependency Cluster",
    priority: "CRITICAL",
    confidence: 99,
    problem: "AnalysisService circle.",
    evidence: "Cycle detected.",
    affectedComponents: ["AnalysisService", "ArchitectureService", "DependencyAnalyzer"],
    expectedArchitecture: "DAG",
    currentArchitecture: "Circular reference",
    expectedBenefit: "Independent deployment",
    estimatedEffort: "HIGH",
    suggestedSteps: ["Use event bus"],
    status: "ACKNOWLEDGED",
  },
  // Pad with 6 more to reach 9
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `rec-pad-${i}`,
    title: [
      "Introduce Domain-Facing Repository Interfaces",
      "Reduce External Provider Coupling",
      "Split High-Complexity Analysis Service",
      "Normalize API Boundary",
      "Introduce Dependency Inversion",
      "Extract Shared Infrastructure Adapter",
    ][i],
    priority: "MEDIUM" as const,
    confidence: 85,
    problem: "Architectural smell detected.",
    evidence: "Heuristic match.",
    affectedComponents: ["ServiceX"],
    expectedArchitecture: "Clean Architecture",
    currentArchitecture: "Tightly Coupled",
    expectedBenefit: "Maintainability",
    estimatedEffort: "LOW" as const,
    suggestedSteps: ["Refactor"],
    status: "OPEN" as const,
  })),
];

const MOCK_EVIDENCE: ArchitectureReviewEvidence[] = [
  { id: "ev-1", type: "Code Structure", description: "ProjectService directly imports PostgresRepository.", findingId: "fnd-1", components: ["ProjectService", "PostgresRepository"] },
  { id: "ev-2", type: "Dependency", description: "ArchitectureService and DependencyAnalyzer form a circular dependency cluster.", findingId: "fnd-2", components: ["ArchitectureService", "DependencyAnalyzer"] },
  { id: "ev-3", type: "Architecture", description: "7 components cross the Application → Infrastructure boundary.", components: ["Multiple"] },
  ...Array.from({ length: 18 }).map((_, i) => ({
    id: `ev-pad-${i}`,
    type: ["Governance", "Repository", "Complexity"][i % 3],
    description: `Automatically detected architectural pattern ${i}`,
    components: [`Component${i}`],
  })),
];

const MOCK_HISTORY: ArchitectureReviewHistory[] = [
  { id: "hist-1", date: "Oct 01, 2026", score: 86, findings: 14, criticalFindings: 1, recommendations: 9, change: "UP" },
  { id: "hist-2", date: "Sep 29, 2026", score: 84, findings: 16, criticalFindings: 2, recommendations: 11, change: "UP" },
  { id: "hist-3", date: "Sep 25, 2026", score: 81, findings: 19, criticalFindings: 3, recommendations: 12, change: "UP" },
  { id: "hist-4", date: "Sep 21, 2026", score: 79, findings: 22, criticalFindings: 3, recommendations: 15, change: "UP" },
  { id: "hist-5", date: "Sep 17, 2026", score: 77, findings: 25, criticalFindings: 4, recommendations: 16, change: "FLAT" },
  { id: "hist-6", date: "Sep 10, 2026", score: 77, findings: 26, criticalFindings: 5, recommendations: 18, change: "DOWN" },
  { id: "hist-7", date: "Sep 01, 2026", score: 80, findings: 20, criticalFindings: 2, recommendations: 10, change: "UP" },
  { id: "hist-8", date: "Aug 25, 2026", score: 75, findings: 30, criticalFindings: 6, recommendations: 22, change: "FLAT" },
];

export const MOCK_AI_REVIEW_DATA: ArchitectureReview = {
  stats: MOCK_STATS,
  scoreBreakdown: {
    overall: 86,
    architecture: 91,
    boundaries: 82,
    dependencies: 79,
    security: 94,
    scalability: 88,
    maintainability: 86,
    performance: 90,
  },
  summary: MOCK_SUMMARY,
  findings: MOCK_FINDINGS,
  recommendations: MOCK_RECOMMENDATIONS,
  evidence: MOCK_EVIDENCE,
  history: MOCK_HISTORY,
  strengths: MOCK_STRENGTHS,
  categories: MOCK_CATEGORIES,
};
