import { Report, ReportActivity, ReportHistoryEntry, ReportStats, ReportSummary } from "@/types/reports-ui";

export const MOCK_REPORT_STATS: ReportStats = {
  total: 12,
  completed: 10,
  inProgress: 1,
  scheduled: 1,
  latestScore: 86,
  coverage: 94,
};

export const MOCK_REPORT_SUMMARY: ReportSummary = {
  title: "Comprehensive Architecture Review",
  score: 86,
  summary: "The repository demonstrates strong architectural layering and service modularity. The primary areas requiring attention are dependency direction, infrastructure boundary leakage, and several high-complexity services.",
  keyObservations: [
    "1 critical architecture finding",
    "3 high-priority findings",
    "7 boundary risks",
    "9 actionable recommendations"
  ]
};

export const MOCK_REPORTS: Report[] = [
  {
    id: "rep-1",
    title: "Comprehensive Architecture Review",
    type: "COMPREHENSIVE",
    status: "COMPLETED",
    score: 86,
    format: "PDF",
    generatedAt: "Oct 01, 21:20",
    duration: "45s",
    coverage: 94,
    summary: "Detailed overview of the entire system architecture.",
    recommendations: ["Fix circular dependencies", "Improve auth boundaries"],
    affectedComponents: ["AuthService", "ProjectService"],
    availableFormats: ["PDF", "HTML", "JSON"],
    findingsCount: 14,
    sections: [
      {
        id: "sec-1",
        title: "Executive Summary",
        content: "Overall architecture is solid but needs dependency cleanup.",
        metrics: [{ label: "Architecture Score", value: 86 }]
      }
    ]
  },
  {
    id: "rep-2",
    title: "Repository Health Report",
    type: "REPOSITORY_ANALYSIS",
    status: "COMPLETED",
    score: 92,
    format: "HTML",
    generatedAt: "Oct 01, 14:30",
    duration: "12s",
    coverage: 100,
    summary: "Repository metadata and health overview.",
    recommendations: ["Update stale dependencies"],
    affectedComponents: ["package.json"],
    availableFormats: ["HTML", "JSON"],
    findingsCount: 5,
    sections: []
  },
  {
    id: "rep-3",
    title: "Dependency Analysis Report",
    type: "DEPENDENCY",
    status: "COMPLETED",
    score: 82,
    format: "JSON",
    generatedAt: "Sep 30, 09:15",
    duration: "18s",
    coverage: 98,
    summary: "Deep dive into module coupling and dependency cycles.",
    recommendations: ["Break cycle in AnalysisService"],
    affectedComponents: ["AnalysisService"],
    availableFormats: ["PDF", "HTML", "JSON"],
    findingsCount: 11,
    sections: []
  },
  {
    id: "rep-4",
    title: "Architecture Evolution Report",
    type: "EVOLUTION",
    status: "COMPLETED",
    score: 84,
    format: "PDF",
    generatedAt: "Sep 29, 11:20",
    duration: "25s",
    coverage: 90,
    summary: "Tracking changes in architecture over time.",
    recommendations: ["Monitor increasing complexity in controllers"],
    affectedComponents: ["APIControllers"],
    availableFormats: ["PDF", "HTML"],
    findingsCount: 7,
    sections: []
  },
  {
    id: "rep-5",
    title: "Governance Compliance Report",
    type: "GOVERNANCE",
    status: "COMPLETED",
    score: 91,
    format: "PDF",
    generatedAt: "Sep 28, 16:45",
    duration: "30s",
    coverage: 100,
    summary: "Policy violation and compliance tracking.",
    recommendations: ["Enforce 100% test coverage for domain"],
    affectedComponents: ["DomainLayer"],
    availableFormats: ["PDF", "HTML", "JSON"],
    findingsCount: 23,
    sections: []
  },
  {
    id: "rep-6",
    title: "Decision Intelligence Report",
    type: "DECISION",
    status: "COMPLETED",
    score: 88,
    format: "HTML",
    generatedAt: "Sep 27, 10:00",
    duration: "15s",
    coverage: 85,
    summary: "ADR compliance and decision tracking.",
    recommendations: ["Document database choice"],
    affectedComponents: ["DatabaseAdapter"],
    availableFormats: ["HTML"],
    findingsCount: 4,
    sections: []
  },
  {
    id: "rep-7",
    title: "AI Architecture Review",
    type: "AI_ARCHITECTURE",
    status: "COMPLETED",
    score: 86,
    format: "PDF",
    generatedAt: "Sep 26, 13:10",
    duration: "60s",
    coverage: 95,
    summary: "AI-assisted architectural insights.",
    recommendations: ["Extract shared infrastructure"],
    affectedComponents: ["SharedKernel"],
    availableFormats: ["PDF", "HTML", "JSON"],
    findingsCount: 12,
    sections: []
  },
  {
    id: "rep-8",
    title: "Security Baseline Report",
    type: "SECURITY_BASELINE",
    status: "COMPLETED",
    score: 95,
    format: "JSON",
    generatedAt: "Sep 25, 08:30",
    duration: "20s",
    coverage: 100,
    summary: "Security static analysis.",
    recommendations: ["Rotate keys"],
    affectedComponents: ["EnvironmentVariables"],
    availableFormats: ["JSON"],
    findingsCount: 2,
    sections: []
  },
  {
    id: "rep-9",
    title: "Technical Debt Report",
    type: "TECHNICAL_DEBT",
    status: "COMPLETED",
    score: 75,
    format: "HTML",
    generatedAt: "Sep 24, 15:45",
    duration: "40s",
    coverage: 92,
    summary: "Accumulated technical debt over last quarter.",
    recommendations: ["Refactor LegacyService"],
    affectedComponents: ["LegacyService"],
    availableFormats: ["HTML", "PDF"],
    findingsCount: 35,
    sections: []
  },
  {
    id: "rep-10",
    title: "Code Quality Report",
    type: "CODE_QUALITY",
    status: "COMPLETED",
    score: 89,
    format: "HTML",
    generatedAt: "Sep 23, 11:15",
    duration: "22s",
    coverage: 98,
    summary: "Linting, complexity, and duplications.",
    recommendations: ["Reduce complexity in controllers"],
    affectedComponents: ["Controllers"],
    availableFormats: ["HTML", "JSON"],
    findingsCount: 18,
    sections: []
  },
  {
    id: "rep-11",
    title: "Performance Analysis Report",
    type: "PERFORMANCE_ANALYSIS",
    status: "GENERATING",
    score: 0,
    format: "PDF",
    generatedAt: "-",
    duration: "-",
    coverage: 0,
    summary: "Generating...",
    recommendations: [],
    affectedComponents: [],
    availableFormats: ["PDF"],
    findingsCount: 0,
    sections: []
  },
  {
    id: "rep-12",
    title: "Executive Architecture Summary",
    type: "EXECUTIVE_SUMMARY",
    status: "SCHEDULED",
    score: 0,
    format: "PDF",
    generatedAt: "-",
    duration: "-",
    coverage: 0,
    summary: "Scheduled for tomorrow.",
    recommendations: [],
    affectedComponents: [],
    availableFormats: ["PDF"],
    findingsCount: 0,
    sections: []
  }
];

export const MOCK_REPORT_HISTORY: ReportHistoryEntry[] = [
  { id: "hist-1", date: "Oct 01, 21:20", reportTitle: "Comprehensive Architecture Review", score: 86, findings: 14, status: "COMPLETED" },
  { id: "hist-2", date: "Oct 01, 14:30", reportTitle: "Repository Health Report", score: 92, findings: 5, status: "COMPLETED" },
  { id: "hist-3", date: "Sep 30, 09:15", reportTitle: "Dependency Analysis Report", score: 82, findings: 11, status: "COMPLETED" },
  { id: "hist-4", date: "Sep 29, 11:20", reportTitle: "Architecture Evolution Report", score: 84, findings: 7, status: "COMPLETED" },
  { id: "hist-5", date: "Sep 28, 16:45", reportTitle: "Governance Compliance Report", score: 91, findings: 23, status: "COMPLETED" },
  { id: "hist-6", date: "Sep 27, 10:00", reportTitle: "Decision Intelligence Report", score: 88, findings: 4, status: "COMPLETED" },
  { id: "hist-7", date: "Sep 26, 13:10", reportTitle: "AI Architecture Review", score: 86, findings: 12, status: "COMPLETED" },
  { id: "hist-8", date: "Sep 25, 08:30", reportTitle: "Security Baseline Report", score: 95, findings: 2, status: "COMPLETED" },
  { id: "hist-9", date: "Sep 24, 15:45", reportTitle: "Technical Debt Report", score: 75, findings: 35, status: "COMPLETED" },
  { id: "hist-10", date: "Sep 23, 11:15", reportTitle: "Code Quality Report", score: 89, findings: 18, status: "COMPLETED" }
];

export const MOCK_REPORT_ACTIVITY: ReportActivity[] = [
  { id: "act-1", date: "Oct 01", event: "Comprehensive Architecture Review generated", reportTitle: "Comprehensive Architecture Review", status: "COMPLETED" },
  { id: "act-2", date: "Oct 01", event: "Governance Compliance Report completed", reportTitle: "Governance Compliance Report", status: "COMPLETED" },
  { id: "act-3", date: "Sep 30", event: "Dependency Analysis Report generated", reportTitle: "Dependency Analysis Report", status: "COMPLETED" },
  { id: "act-4", date: "Sep 29", event: "Architecture Evolution Report updated", reportTitle: "Architecture Evolution Report", status: "COMPLETED" },
  { id: "act-5", date: "Sep 27", event: "Technical Debt Report generated", reportTitle: "Technical Debt Report", status: "COMPLETED" },
];
