"""core_workspace_refinements

Revision ID: cf0992cbca22
Revises: 8a96f14607fb
Create Date: 2026-07-10 11:12:22.774456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0992cbca22'
down_revision: Union[str, None] = '8a96f14607fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_repositories_project_id_status', 'repositories', ['project_id', 'status'], unique=False)
    op.create_unique_constraint('uq_repositories_project_clone_url', 'repositories', ['project_id', 'clone_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repositories_project_clone_url', 'repositories', type_='unique')
    op.drop_index('ix_repositories_project_id_status', table_name='repositories')
    # ### end Alembic commands ###
