"""update_project_table_slug

Revision ID: 91692e15d625
Revises: cf0992cbca22
Create Date: 2026-07-13 12:11:57.625603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91692e15d625'
down_revision: Union[str, None] = 'cf0992cbca22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slug', sa.String(length=150), nullable=False))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('projects', 'visibility',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PRIVATE', 'PUBLIC', name='projectvisibility', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_projects_owner_name'), 'projects', type_='unique')
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_unique_constraint('uq_projects_owner_slug', 'projects', ['owner_id', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_owner_slug', 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.create_unique_constraint(op.f('uq_projects_owner_name'), 'projects', ['owner_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('projects', 'visibility',
               existing_type=sa.Enum('PRIVATE', 'PUBLIC', name='projectvisibility', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('projects', 'slug')
    # ### end Alembic commands ###
