"""Technical Debt Rule Interface module."""

from abc import ABC, abstractmethod
from typing import Any, Iterable

from app.technical_debt.enums import TechnicalDebtCategory, TechnicalDebtSeverity
from app.technical_debt.models import TechnicalDebtItem


class TechnicalDebtRule(ABC):
    """Abstract base class representing a codebase technical debt detection rule."""

    @property
    @abstractmethod
    def rule_id(self) -> str:
        """Unique identifier key for the rule."""
        pass

    @property
    @abstractmethod
    def category(self) -> TechnicalDebtCategory:
        """The technical debt category grouping of findings produced by this rule."""
        pass

    @property
    @abstractmethod
    def severity(self) -> TechnicalDebtSeverity:
        """The default severity level class for findings generated by this rule."""
        pass

    @property
    @abstractmethod
    def title(self) -> str:
        """Short descriptive title identifying the rule."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Detailed documentation explaining the rule guidelines and purpose."""
        pass

    @abstractmethod
    def evaluate(self, context: Any, **kwargs) -> Iterable[TechnicalDebtItem]:
        """Evaluates the rule against context findings and yields technical debt items."""
        pass
