"""AI Analysis Domain Enums module.

Defines StrEnum categories for analysis types, severity levels, recommendations,
and trigger modes.
"""

from enum import StrEnum


class AnalysisType(StrEnum):
    """Supported analysis categories performed on the codebase."""

    CODE_QUALITY = "code_quality"
    SECURITY = "security"
    PERFORMANCE = "performance"
    DESIGN = "design"
    STYLE = "style"


class AnalysisSeverity(StrEnum):
    """Impact severity levels assigned to analysis findings."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class RecommendationStatus(StrEnum):
    """Lifecycle statuses for recommendations generated by the AI analysis engine."""

    OPEN = "open"
    RESOLVED = "resolved"
    IGNORED = "ignored"
    WONT_FIX = "wont_fix"


class AnalysisTrigger(StrEnum):
    """Indicates how the analysis run was initiated."""

    MANUAL = "manual"
    COMMIT = "commit"
    PR = "pr"
    SCHEDULED = "scheduled"
